name: mtlqr_app
description: A Flutter app to scan QR codes and connect to a remote MySQL database.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  qr_code_scanner: ^1.0.1 
  http: ^0.13.6  # vai jaunākā versija
  shared_preferences: ^2.2.2
  flutter_barcode_scanner: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
