name: MTLQR
description: "MTL pārvaldības rīks"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2
  http: ^0.13.6
  shared_preferences: ^2.2.2
  mobile_scanner: ^6.0.6
  geolocator: ^10.1.0
  permission_handler: ^11.0.1
  cupertino_icons: ^1.0.8
  sms_autofill: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/app.png"  